CREATE TABLE IF NOT EXISTS BOX(
    ID INTEGER PRIMARY KEY,
    CONTAINED_IN INTEGER
);
CREATE TABLE IF NOT EXISTS ITEM(
    ID INTEGER PRIMARY KEY,
    CONTAINED_IN INTEGER REFERENCES BOX(ID),
    COLOR VARCHAR(100)
);

-- CREATE UNIQUE INDEX item_id_index ON public.item(id);
-- CREATE UNIQUE INDEX box_id_index ON public.box(id);

DELETE FROM ITEM;
DELETE FROM BOX;